version: "3.8"

services:
  # Server container
  server:
    build:
      context: ./server
    expose:
      - $SERVER_PORT
    environment:
      APP_SERVER_PORT: $SERVER_PORT
    ports:
      - $SERVER_PORT:$SERVER_PORT
    volumes:
      - ./server/:/usr/app/
      - /usr/app/node_modules
    command: yarn server:watch
