# Workflow for CI.

name: ci

on:
  push:
    branches: [master]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.0

      - name: Install Server Dependencies
        run: cd server && yarn

      - name: Install Client Dependencies
        run: cd web && yarn

      - name: Tests
        run: cd web && yarn test

      - name: Linting
        run: cd server && yarn lint && cd .. && cd web && yarn lint
